dist: trusty
sudo: required
language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      env: FEATURES="avx-accel" RUSTFLAGS="-C target-cpu=native"

    # Supplemental checks
    - env: CI_MODE="format-diff"
      rust: nightly
    - env: CI_MODE="clippy" ALLOW_FAILURE=true
      rust: nightly

  allow_failures:
    - env: ALLOW_FAILURE=true

cache: cargo

script:
  - cargo update
  - ./.travis/travis.sh "${CI_MODE:-}" "${FEATURES:-}" "$TRAVIS_RUST_VERSION"
